utils = {}

return {
    "pseudo_random",
    "json",
    "lua_memory_usage",
    "bonus",
    "bubbles",
    "creatures",
    "damage",
    "funcs",
    "math",
    "particles",
    "popups",
    "projectile",
    "string",
    "table",
    "vector",
    "json",
    "item_collector",
    "talent_writer",
    "ability_writer",
    "kv_writter",
    "msg",
    "utils",
    -- "crash_detector",
}