LinkLuaModifier("modifier_respawn_bonus","scripts/vscripts/modifiers/modifier_respawn_bonus.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_disconnected","scripts/vscripts/modifiers/modifier_disconnected.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_provides_vision","scripts/vscripts/modifiers/modifier_provides_vision.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_fighting_area_poison","scripts/vscripts/modifiers/modifier_fighting_area_poison.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_bom_truesight","scripts/vscripts/modifiers/modifier_bom_truesight.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_disconnect_detection","scripts/vscripts/modifiers/modifier_disconnect_detection.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_status_resistance","scripts/vscripts/modifiers/modifier_hero_status_resistance.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_status_resistance_jinmin","scripts/vscripts/modifiers/modifier_hero_status_resistance_jinmin.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_movespeed_bonus_constant","scripts/vscripts/modifiers/modifier_hero_movespeed_bonus_constant.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_movespeed_bonus_constant_ranged","scripts/vscripts/modifiers/modifier_hero_movespeed_bonus_constant_ranged.lua",LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_waiting_for_precache","scripts/vscripts/modifiers/modifier_waiting_for_precache.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_daytime_vision_range_bonus","scripts/vscripts/modifiers/modifier_daytime_vision_range_bonus.lua",LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_fearless_brave","scripts/vscripts/modifiers/modifier_fearless_brave.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_passive_gold_bonus","scripts/vscripts/modifiers/modifier_passive_gold_bonus.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_shame_of_deserter","scripts/vscripts/modifiers/modifier_shame_of_deserter.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_shame_of_deserter_tooltip","scripts/vscripts/modifiers/modifier_shame_of_deserter_tooltip.lua",LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_candy_bucket","scripts/vscripts/modifiers/modifier_candy_bucket.lua",LUA_MODIFIER_MOTION_NONE)

LinkLuaModifier("modifier_sniper_take_aim_fix","scripts/vscripts/modifiers/modifier_sniper_take_aim_fix.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_cooldown_percentage","scripts/vscripts/modifiers/modifier_hero_cooldown_percentage.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_npc_dota_hero_pangolier_1","scripts/vscripts/modifiers/modifier_npc_dota_hero_pangolier_1.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_npc_dota_hero_enigma_1","scripts/vscripts/modifiers/modifier_npc_dota_hero_enigma_1.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_npc_dota_hero_night_stalker_1","scripts/vscripts/modifiers/modifier_npc_dota_hero_night_stalker_1.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_npc_dota_hero_razor_1","scripts/vscripts/modifiers/modifier_npc_dota_hero_razor_1.lua",LUA_MODIFIER_MOTION_NONE)
LinkLuaModifier("modifier_hero_attradd","scripts/vscripts/modifiers/modifier_hero_attradd.lua",LUA_MODIFIER_MOTION_NONE)